// Code generated by ent, DO NOT EDIT.

package cancelorderflowrun

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the cancelorderflowrun type in the database.
	Label = "cancel_order_flow_run"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldInput holds the string denoting the input field in the database.
	FieldInput = "input"
	// FieldCurrentStep holds the string denoting the current_step field in the database.
	FieldCurrentStep = "current_step"
	// FieldAttempt holds the string denoting the attempt field in the database.
	FieldAttempt = "attempt"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldResults holds the string denoting the results field in the database.
	FieldResults = "results"
	// FieldRetryAfter holds the string denoting the retry_after field in the database.
	FieldRetryAfter = "retry_after"
	// FieldTraceContext holds the string denoting the trace_context field in the database.
	FieldTraceContext = "trace_context"
	// FieldSelfWas holds the string denoting the self_was field in the database.
	FieldSelfWas = "self_was"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// Table holds the table name of the cancelorderflowrun in the database.
	Table = "cancel_order_flow_runs"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "cancel_order_flow_runs"
	// OwnerInverseTable is the table name for the Order entity.
	// It exists in this package in order to avoid circular dependency with the "order" package.
	OwnerInverseTable = "orders"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "cancel_order_flow_run_owner"
)

// Columns holds all SQL columns for cancelorderflowrun fields.
var Columns = []string{
	FieldID,
	FieldState,
	FieldInput,
	FieldCurrentStep,
	FieldAttempt,
	FieldLastError,
	FieldResults,
	FieldRetryAfter,
	FieldTraceContext,
	FieldSelfWas,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldStartedAt,
	FieldFinishedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "cancel_order_flow_runs"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"cancel_order_flow_run_owner",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/smintz/entflow/internal/testdata/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultAttempt holds the default value on creation for the "attempt" field.
	DefaultAttempt int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// State defines the type for the "state" enum field.
type State string

// StatePending is the default value of the State enum.
const DefaultState = StatePending

// State values.
const (
	StatePending              State = "pending"
	StateRunning              State = "running"
	StateDone                 State = "done"
	StateCancelled            State = "cancelled"
	StateFailedCancel         State = "failed:cancel"
	StateFailedRefund         State = "failed:refund"
	StateFailedOrderCancelled State = "failed:order.cancelled"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StatePending, StateRunning, StateDone, StateCancelled, StateFailedCancel, StateFailedRefund, StateFailedOrderCancelled:
		return nil
	default:
		return fmt.Errorf("cancelorderflowrun: invalid enum value for state field: %q", s)
	}
}

// OrderOption defines the ordering options for the CancelOrderFlowRun queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByCurrentStep orders the results by the current_step field.
func ByCurrentStep(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentStep, opts...).ToFunc()
}

// ByAttempt orders the results by the attempt field.
func ByAttempt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttempt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByRetryAfter orders the results by the retry_after field.
func ByRetryAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetryAfter, opts...).ToFunc()
}

// ByTraceContext orders the results by the trace_context field.
func ByTraceContext(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTraceContext, opts...).ToFunc()
}

// BySelfWas orders the results by the self_was field.
func BySelfWas(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSelfWas, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, OwnerTable, OwnerColumn),
	)
}
