// Code generated by ent, DO NOT EDIT.

package cancelorderflowrun

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/smintz/entflow/internal/testdata/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldLTE(FieldID, id))
}

// Input applies equality check predicate on the "input" field. It's identical to InputEQ.
func Input(v []byte) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldInput, v))
}

// CurrentStep applies equality check predicate on the "current_step" field. It's identical to CurrentStepEQ.
func CurrentStep(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldCurrentStep, v))
}

// Attempt applies equality check predicate on the "attempt" field. It's identical to AttemptEQ.
func Attempt(v int) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldAttempt, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldLastError, v))
}

// RetryAfter applies equality check predicate on the "retry_after" field. It's identical to RetryAfterEQ.
func RetryAfter(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldRetryAfter, v))
}

// TraceContext applies equality check predicate on the "trace_context" field. It's identical to TraceContextEQ.
func TraceContext(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldTraceContext, v))
}

// SelfWas applies equality check predicate on the "self_was" field. It's identical to SelfWasEQ.
func SelfWas(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldSelfWas, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldUpdatedAt, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldFinishedAt, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v State) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v State) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...State) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...State) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNotIn(FieldState, vs...))
}

// InputEQ applies the EQ predicate on the "input" field.
func InputEQ(v []byte) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldInput, v))
}

// InputNEQ applies the NEQ predicate on the "input" field.
func InputNEQ(v []byte) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNEQ(FieldInput, v))
}

// InputIn applies the In predicate on the "input" field.
func InputIn(vs ...[]byte) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldIn(FieldInput, vs...))
}

// InputNotIn applies the NotIn predicate on the "input" field.
func InputNotIn(vs ...[]byte) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNotIn(FieldInput, vs...))
}

// InputGT applies the GT predicate on the "input" field.
func InputGT(v []byte) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldGT(FieldInput, v))
}

// InputGTE applies the GTE predicate on the "input" field.
func InputGTE(v []byte) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldGTE(FieldInput, v))
}

// InputLT applies the LT predicate on the "input" field.
func InputLT(v []byte) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldLT(FieldInput, v))
}

// InputLTE applies the LTE predicate on the "input" field.
func InputLTE(v []byte) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldLTE(FieldInput, v))
}

// CurrentStepEQ applies the EQ predicate on the "current_step" field.
func CurrentStepEQ(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldCurrentStep, v))
}

// CurrentStepNEQ applies the NEQ predicate on the "current_step" field.
func CurrentStepNEQ(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNEQ(FieldCurrentStep, v))
}

// CurrentStepIn applies the In predicate on the "current_step" field.
func CurrentStepIn(vs ...string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldIn(FieldCurrentStep, vs...))
}

// CurrentStepNotIn applies the NotIn predicate on the "current_step" field.
func CurrentStepNotIn(vs ...string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNotIn(FieldCurrentStep, vs...))
}

// CurrentStepGT applies the GT predicate on the "current_step" field.
func CurrentStepGT(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldGT(FieldCurrentStep, v))
}

// CurrentStepGTE applies the GTE predicate on the "current_step" field.
func CurrentStepGTE(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldGTE(FieldCurrentStep, v))
}

// CurrentStepLT applies the LT predicate on the "current_step" field.
func CurrentStepLT(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldLT(FieldCurrentStep, v))
}

// CurrentStepLTE applies the LTE predicate on the "current_step" field.
func CurrentStepLTE(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldLTE(FieldCurrentStep, v))
}

// CurrentStepContains applies the Contains predicate on the "current_step" field.
func CurrentStepContains(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldContains(FieldCurrentStep, v))
}

// CurrentStepHasPrefix applies the HasPrefix predicate on the "current_step" field.
func CurrentStepHasPrefix(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldHasPrefix(FieldCurrentStep, v))
}

// CurrentStepHasSuffix applies the HasSuffix predicate on the "current_step" field.
func CurrentStepHasSuffix(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldHasSuffix(FieldCurrentStep, v))
}

// CurrentStepIsNil applies the IsNil predicate on the "current_step" field.
func CurrentStepIsNil() predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldIsNull(FieldCurrentStep))
}

// CurrentStepNotNil applies the NotNil predicate on the "current_step" field.
func CurrentStepNotNil() predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNotNull(FieldCurrentStep))
}

// CurrentStepEqualFold applies the EqualFold predicate on the "current_step" field.
func CurrentStepEqualFold(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEqualFold(FieldCurrentStep, v))
}

// CurrentStepContainsFold applies the ContainsFold predicate on the "current_step" field.
func CurrentStepContainsFold(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldContainsFold(FieldCurrentStep, v))
}

// AttemptEQ applies the EQ predicate on the "attempt" field.
func AttemptEQ(v int) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldAttempt, v))
}

// AttemptNEQ applies the NEQ predicate on the "attempt" field.
func AttemptNEQ(v int) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNEQ(FieldAttempt, v))
}

// AttemptIn applies the In predicate on the "attempt" field.
func AttemptIn(vs ...int) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldIn(FieldAttempt, vs...))
}

// AttemptNotIn applies the NotIn predicate on the "attempt" field.
func AttemptNotIn(vs ...int) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNotIn(FieldAttempt, vs...))
}

// AttemptGT applies the GT predicate on the "attempt" field.
func AttemptGT(v int) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldGT(FieldAttempt, v))
}

// AttemptGTE applies the GTE predicate on the "attempt" field.
func AttemptGTE(v int) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldGTE(FieldAttempt, v))
}

// AttemptLT applies the LT predicate on the "attempt" field.
func AttemptLT(v int) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldLT(FieldAttempt, v))
}

// AttemptLTE applies the LTE predicate on the "attempt" field.
func AttemptLTE(v int) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldLTE(FieldAttempt, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldContainsFold(FieldLastError, v))
}

// ResultsIsNil applies the IsNil predicate on the "results" field.
func ResultsIsNil() predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldIsNull(FieldResults))
}

// ResultsNotNil applies the NotNil predicate on the "results" field.
func ResultsNotNil() predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNotNull(FieldResults))
}

// RetryAfterEQ applies the EQ predicate on the "retry_after" field.
func RetryAfterEQ(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldRetryAfter, v))
}

// RetryAfterNEQ applies the NEQ predicate on the "retry_after" field.
func RetryAfterNEQ(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNEQ(FieldRetryAfter, v))
}

// RetryAfterIn applies the In predicate on the "retry_after" field.
func RetryAfterIn(vs ...time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldIn(FieldRetryAfter, vs...))
}

// RetryAfterNotIn applies the NotIn predicate on the "retry_after" field.
func RetryAfterNotIn(vs ...time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNotIn(FieldRetryAfter, vs...))
}

// RetryAfterGT applies the GT predicate on the "retry_after" field.
func RetryAfterGT(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldGT(FieldRetryAfter, v))
}

// RetryAfterGTE applies the GTE predicate on the "retry_after" field.
func RetryAfterGTE(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldGTE(FieldRetryAfter, v))
}

// RetryAfterLT applies the LT predicate on the "retry_after" field.
func RetryAfterLT(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldLT(FieldRetryAfter, v))
}

// RetryAfterLTE applies the LTE predicate on the "retry_after" field.
func RetryAfterLTE(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldLTE(FieldRetryAfter, v))
}

// RetryAfterIsNil applies the IsNil predicate on the "retry_after" field.
func RetryAfterIsNil() predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldIsNull(FieldRetryAfter))
}

// RetryAfterNotNil applies the NotNil predicate on the "retry_after" field.
func RetryAfterNotNil() predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNotNull(FieldRetryAfter))
}

// TraceContextEQ applies the EQ predicate on the "trace_context" field.
func TraceContextEQ(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldTraceContext, v))
}

// TraceContextNEQ applies the NEQ predicate on the "trace_context" field.
func TraceContextNEQ(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNEQ(FieldTraceContext, v))
}

// TraceContextIn applies the In predicate on the "trace_context" field.
func TraceContextIn(vs ...string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldIn(FieldTraceContext, vs...))
}

// TraceContextNotIn applies the NotIn predicate on the "trace_context" field.
func TraceContextNotIn(vs ...string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNotIn(FieldTraceContext, vs...))
}

// TraceContextGT applies the GT predicate on the "trace_context" field.
func TraceContextGT(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldGT(FieldTraceContext, v))
}

// TraceContextGTE applies the GTE predicate on the "trace_context" field.
func TraceContextGTE(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldGTE(FieldTraceContext, v))
}

// TraceContextLT applies the LT predicate on the "trace_context" field.
func TraceContextLT(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldLT(FieldTraceContext, v))
}

// TraceContextLTE applies the LTE predicate on the "trace_context" field.
func TraceContextLTE(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldLTE(FieldTraceContext, v))
}

// TraceContextContains applies the Contains predicate on the "trace_context" field.
func TraceContextContains(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldContains(FieldTraceContext, v))
}

// TraceContextHasPrefix applies the HasPrefix predicate on the "trace_context" field.
func TraceContextHasPrefix(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldHasPrefix(FieldTraceContext, v))
}

// TraceContextHasSuffix applies the HasSuffix predicate on the "trace_context" field.
func TraceContextHasSuffix(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldHasSuffix(FieldTraceContext, v))
}

// TraceContextIsNil applies the IsNil predicate on the "trace_context" field.
func TraceContextIsNil() predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldIsNull(FieldTraceContext))
}

// TraceContextNotNil applies the NotNil predicate on the "trace_context" field.
func TraceContextNotNil() predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNotNull(FieldTraceContext))
}

// TraceContextEqualFold applies the EqualFold predicate on the "trace_context" field.
func TraceContextEqualFold(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEqualFold(FieldTraceContext, v))
}

// TraceContextContainsFold applies the ContainsFold predicate on the "trace_context" field.
func TraceContextContainsFold(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldContainsFold(FieldTraceContext, v))
}

// SelfWasEQ applies the EQ predicate on the "self_was" field.
func SelfWasEQ(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldSelfWas, v))
}

// SelfWasNEQ applies the NEQ predicate on the "self_was" field.
func SelfWasNEQ(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNEQ(FieldSelfWas, v))
}

// SelfWasIn applies the In predicate on the "self_was" field.
func SelfWasIn(vs ...string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldIn(FieldSelfWas, vs...))
}

// SelfWasNotIn applies the NotIn predicate on the "self_was" field.
func SelfWasNotIn(vs ...string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNotIn(FieldSelfWas, vs...))
}

// SelfWasGT applies the GT predicate on the "self_was" field.
func SelfWasGT(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldGT(FieldSelfWas, v))
}

// SelfWasGTE applies the GTE predicate on the "self_was" field.
func SelfWasGTE(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldGTE(FieldSelfWas, v))
}

// SelfWasLT applies the LT predicate on the "self_was" field.
func SelfWasLT(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldLT(FieldSelfWas, v))
}

// SelfWasLTE applies the LTE predicate on the "self_was" field.
func SelfWasLTE(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldLTE(FieldSelfWas, v))
}

// SelfWasContains applies the Contains predicate on the "self_was" field.
func SelfWasContains(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldContains(FieldSelfWas, v))
}

// SelfWasHasPrefix applies the HasPrefix predicate on the "self_was" field.
func SelfWasHasPrefix(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldHasPrefix(FieldSelfWas, v))
}

// SelfWasHasSuffix applies the HasSuffix predicate on the "self_was" field.
func SelfWasHasSuffix(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldHasSuffix(FieldSelfWas, v))
}

// SelfWasIsNil applies the IsNil predicate on the "self_was" field.
func SelfWasIsNil() predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldIsNull(FieldSelfWas))
}

// SelfWasNotNil applies the NotNil predicate on the "self_was" field.
func SelfWasNotNil() predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNotNull(FieldSelfWas))
}

// SelfWasEqualFold applies the EqualFold predicate on the "self_was" field.
func SelfWasEqualFold(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEqualFold(FieldSelfWas, v))
}

// SelfWasContainsFold applies the ContainsFold predicate on the "self_was" field.
func SelfWasContainsFold(v string) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldContainsFold(FieldSelfWas, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldLTE(FieldUpdatedAt, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNotNull(FieldStartedAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.FieldNotNull(FieldFinishedAt))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.Order) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CancelOrderFlowRun) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CancelOrderFlowRun) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CancelOrderFlowRun) predicate.CancelOrderFlowRun {
	return predicate.CancelOrderFlowRun(sql.NotPredicates(p))
}
