// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entflow/internal/testdata/ent/cancelorderflowrun"
	"github.com/smintz/entflow/internal/testdata/ent/order"
)

// CancelOrderFlowRunCreate is the builder for creating a CancelOrderFlowRun entity.
type CancelOrderFlowRunCreate struct {
	config
	mutation *CancelOrderFlowRunMutation
	hooks    []Hook
}

// SetState sets the "state" field.
func (_c *CancelOrderFlowRunCreate) SetState(v cancelorderflowrun.State) *CancelOrderFlowRunCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *CancelOrderFlowRunCreate) SetNillableState(v *cancelorderflowrun.State) *CancelOrderFlowRunCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetInput sets the "input" field.
func (_c *CancelOrderFlowRunCreate) SetInput(v []byte) *CancelOrderFlowRunCreate {
	_c.mutation.SetInput(v)
	return _c
}

// SetCurrentStep sets the "current_step" field.
func (_c *CancelOrderFlowRunCreate) SetCurrentStep(v string) *CancelOrderFlowRunCreate {
	_c.mutation.SetCurrentStep(v)
	return _c
}

// SetNillableCurrentStep sets the "current_step" field if the given value is not nil.
func (_c *CancelOrderFlowRunCreate) SetNillableCurrentStep(v *string) *CancelOrderFlowRunCreate {
	if v != nil {
		_c.SetCurrentStep(*v)
	}
	return _c
}

// SetAttempt sets the "attempt" field.
func (_c *CancelOrderFlowRunCreate) SetAttempt(v int) *CancelOrderFlowRunCreate {
	_c.mutation.SetAttempt(v)
	return _c
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (_c *CancelOrderFlowRunCreate) SetNillableAttempt(v *int) *CancelOrderFlowRunCreate {
	if v != nil {
		_c.SetAttempt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *CancelOrderFlowRunCreate) SetLastError(v string) *CancelOrderFlowRunCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *CancelOrderFlowRunCreate) SetNillableLastError(v *string) *CancelOrderFlowRunCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetResults sets the "results" field.
func (_c *CancelOrderFlowRunCreate) SetResults(v map[string]json.RawMessage) *CancelOrderFlowRunCreate {
	_c.mutation.SetResults(v)
	return _c
}

// SetRetryAfter sets the "retry_after" field.
func (_c *CancelOrderFlowRunCreate) SetRetryAfter(v time.Time) *CancelOrderFlowRunCreate {
	_c.mutation.SetRetryAfter(v)
	return _c
}

// SetNillableRetryAfter sets the "retry_after" field if the given value is not nil.
func (_c *CancelOrderFlowRunCreate) SetNillableRetryAfter(v *time.Time) *CancelOrderFlowRunCreate {
	if v != nil {
		_c.SetRetryAfter(*v)
	}
	return _c
}

// SetTraceContext sets the "trace_context" field.
func (_c *CancelOrderFlowRunCreate) SetTraceContext(v string) *CancelOrderFlowRunCreate {
	_c.mutation.SetTraceContext(v)
	return _c
}

// SetNillableTraceContext sets the "trace_context" field if the given value is not nil.
func (_c *CancelOrderFlowRunCreate) SetNillableTraceContext(v *string) *CancelOrderFlowRunCreate {
	if v != nil {
		_c.SetTraceContext(*v)
	}
	return _c
}

// SetSelfWas sets the "self_was" field.
func (_c *CancelOrderFlowRunCreate) SetSelfWas(v string) *CancelOrderFlowRunCreate {
	_c.mutation.SetSelfWas(v)
	return _c
}

// SetNillableSelfWas sets the "self_was" field if the given value is not nil.
func (_c *CancelOrderFlowRunCreate) SetNillableSelfWas(v *string) *CancelOrderFlowRunCreate {
	if v != nil {
		_c.SetSelfWas(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CancelOrderFlowRunCreate) SetCreatedAt(v time.Time) *CancelOrderFlowRunCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CancelOrderFlowRunCreate) SetNillableCreatedAt(v *time.Time) *CancelOrderFlowRunCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CancelOrderFlowRunCreate) SetUpdatedAt(v time.Time) *CancelOrderFlowRunCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CancelOrderFlowRunCreate) SetNillableUpdatedAt(v *time.Time) *CancelOrderFlowRunCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *CancelOrderFlowRunCreate) SetStartedAt(v time.Time) *CancelOrderFlowRunCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *CancelOrderFlowRunCreate) SetNillableStartedAt(v *time.Time) *CancelOrderFlowRunCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *CancelOrderFlowRunCreate) SetFinishedAt(v time.Time) *CancelOrderFlowRunCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *CancelOrderFlowRunCreate) SetNillableFinishedAt(v *time.Time) *CancelOrderFlowRunCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetOwnerID sets the "owner" edge to the Order entity by ID.
func (_c *CancelOrderFlowRunCreate) SetOwnerID(id int) *CancelOrderFlowRunCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetOwner sets the "owner" edge to the Order entity.
func (_c *CancelOrderFlowRunCreate) SetOwner(v *Order) *CancelOrderFlowRunCreate {
	return _c.SetOwnerID(v.ID)
}

// Mutation returns the CancelOrderFlowRunMutation object of the builder.
func (_c *CancelOrderFlowRunCreate) Mutation() *CancelOrderFlowRunMutation {
	return _c.mutation
}

// Save creates the CancelOrderFlowRun in the database.
func (_c *CancelOrderFlowRunCreate) Save(ctx context.Context) (*CancelOrderFlowRun, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CancelOrderFlowRunCreate) SaveX(ctx context.Context) *CancelOrderFlowRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CancelOrderFlowRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CancelOrderFlowRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CancelOrderFlowRunCreate) defaults() {
	if _, ok := _c.mutation.State(); !ok {
		v := cancelorderflowrun.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.Attempt(); !ok {
		v := cancelorderflowrun.DefaultAttempt
		_c.mutation.SetAttempt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := cancelorderflowrun.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := cancelorderflowrun.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CancelOrderFlowRunCreate) check() error {
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "CancelOrderFlowRun.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := cancelorderflowrun.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "CancelOrderFlowRun.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Input(); !ok {
		return &ValidationError{Name: "input", err: errors.New(`ent: missing required field "CancelOrderFlowRun.input"`)}
	}
	if _, ok := _c.mutation.Attempt(); !ok {
		return &ValidationError{Name: "attempt", err: errors.New(`ent: missing required field "CancelOrderFlowRun.attempt"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CancelOrderFlowRun.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CancelOrderFlowRun.updated_at"`)}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "CancelOrderFlowRun.owner"`)}
	}
	return nil
}

func (_c *CancelOrderFlowRunCreate) sqlSave(ctx context.Context) (*CancelOrderFlowRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CancelOrderFlowRunCreate) createSpec() (*CancelOrderFlowRun, *sqlgraph.CreateSpec) {
	var (
		_node = &CancelOrderFlowRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cancelorderflowrun.Table, sqlgraph.NewFieldSpec(cancelorderflowrun.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(cancelorderflowrun.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.Input(); ok {
		_spec.SetField(cancelorderflowrun.FieldInput, field.TypeBytes, value)
		_node.Input = value
	}
	if value, ok := _c.mutation.CurrentStep(); ok {
		_spec.SetField(cancelorderflowrun.FieldCurrentStep, field.TypeString, value)
		_node.CurrentStep = value
	}
	if value, ok := _c.mutation.Attempt(); ok {
		_spec.SetField(cancelorderflowrun.FieldAttempt, field.TypeInt, value)
		_node.Attempt = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(cancelorderflowrun.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.Results(); ok {
		_spec.SetField(cancelorderflowrun.FieldResults, field.TypeJSON, value)
		_node.Results = value
	}
	if value, ok := _c.mutation.RetryAfter(); ok {
		_spec.SetField(cancelorderflowrun.FieldRetryAfter, field.TypeTime, value)
		_node.RetryAfter = &value
	}
	if value, ok := _c.mutation.TraceContext(); ok {
		_spec.SetField(cancelorderflowrun.FieldTraceContext, field.TypeString, value)
		_node.TraceContext = value
	}
	if value, ok := _c.mutation.SelfWas(); ok {
		_spec.SetField(cancelorderflowrun.FieldSelfWas, field.TypeString, value)
		_node.SelfWas = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(cancelorderflowrun.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(cancelorderflowrun.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(cancelorderflowrun.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(cancelorderflowrun.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   cancelorderflowrun.OwnerTable,
			Columns: []string{cancelorderflowrun.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.cancel_order_flow_run_owner = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CancelOrderFlowRunCreateBulk is the builder for creating many CancelOrderFlowRun entities in bulk.
type CancelOrderFlowRunCreateBulk struct {
	config
	err      error
	builders []*CancelOrderFlowRunCreate
}

// Save creates the CancelOrderFlowRun entities in the database.
func (_c *CancelOrderFlowRunCreateBulk) Save(ctx context.Context) ([]*CancelOrderFlowRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CancelOrderFlowRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CancelOrderFlowRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CancelOrderFlowRunCreateBulk) SaveX(ctx context.Context) []*CancelOrderFlowRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CancelOrderFlowRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CancelOrderFlowRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
