// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/smintz/entflow/internal/testdata/ent/cancelorderflowrun"
	"github.com/smintz/entflow/internal/testdata/ent/order"
)

// CancelOrderFlowRun is the model entity for the CancelOrderFlowRun schema.
type CancelOrderFlowRun struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// State holds the value of the "state" field.
	State cancelorderflowrun.State `json:"state,omitempty"`
	// Input holds the value of the "input" field.
	Input []byte `json:"input,omitempty"`
	// CurrentStep holds the value of the "current_step" field.
	CurrentStep string `json:"current_step,omitempty"`
	// Attempt holds the value of the "attempt" field.
	Attempt int `json:"attempt,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError string `json:"last_error,omitempty"`
	// Results holds the value of the "results" field.
	Results map[string]json.RawMessage `json:"results,omitempty"`
	// RetryAfter holds the value of the "retry_after" field.
	RetryAfter *time.Time `json:"retry_after,omitempty"`
	// TraceContext holds the value of the "trace_context" field.
	TraceContext string `json:"trace_context,omitempty"`
	// SelfWas holds the value of the "self_was" field.
	SelfWas string `json:"self_was,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CancelOrderFlowRunQuery when eager-loading is set.
	Edges                       CancelOrderFlowRunEdges `json:"edges"`
	cancel_order_flow_run_owner *int
	selectValues                sql.SelectValues
}

// CancelOrderFlowRunEdges holds the relations/edges for other nodes in the graph.
type CancelOrderFlowRunEdges struct {
	// Owner holds the value of the owner edge.
	Owner *Order `json:"owner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CancelOrderFlowRunEdges) OwnerOrErr() (*Order, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: order.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CancelOrderFlowRun) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cancelorderflowrun.FieldInput, cancelorderflowrun.FieldResults:
			values[i] = new([]byte)
		case cancelorderflowrun.FieldID, cancelorderflowrun.FieldAttempt:
			values[i] = new(sql.NullInt64)
		case cancelorderflowrun.FieldState, cancelorderflowrun.FieldCurrentStep, cancelorderflowrun.FieldLastError, cancelorderflowrun.FieldTraceContext, cancelorderflowrun.FieldSelfWas:
			values[i] = new(sql.NullString)
		case cancelorderflowrun.FieldRetryAfter, cancelorderflowrun.FieldCreatedAt, cancelorderflowrun.FieldUpdatedAt, cancelorderflowrun.FieldStartedAt, cancelorderflowrun.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		case cancelorderflowrun.ForeignKeys[0]: // cancel_order_flow_run_owner
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CancelOrderFlowRun fields.
func (_m *CancelOrderFlowRun) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cancelorderflowrun.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case cancelorderflowrun.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = cancelorderflowrun.State(value.String)
			}
		case cancelorderflowrun.FieldInput:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field input", values[i])
			} else if value != nil {
				_m.Input = *value
			}
		case cancelorderflowrun.FieldCurrentStep:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field current_step", values[i])
			} else if value.Valid {
				_m.CurrentStep = value.String
			}
		case cancelorderflowrun.FieldAttempt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt", values[i])
			} else if value.Valid {
				_m.Attempt = int(value.Int64)
			}
		case cancelorderflowrun.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		case cancelorderflowrun.FieldResults:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field results", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Results); err != nil {
					return fmt.Errorf("unmarshal field results: %w", err)
				}
			}
		case cancelorderflowrun.FieldRetryAfter:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field retry_after", values[i])
			} else if value.Valid {
				_m.RetryAfter = new(time.Time)
				*_m.RetryAfter = value.Time
			}
		case cancelorderflowrun.FieldTraceContext:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trace_context", values[i])
			} else if value.Valid {
				_m.TraceContext = value.String
			}
		case cancelorderflowrun.FieldSelfWas:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field self_was", values[i])
			} else if value.Valid {
				_m.SelfWas = value.String
			}
		case cancelorderflowrun.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case cancelorderflowrun.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case cancelorderflowrun.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case cancelorderflowrun.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case cancelorderflowrun.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field cancel_order_flow_run_owner", value)
			} else if value.Valid {
				_m.cancel_order_flow_run_owner = new(int)
				*_m.cancel_order_flow_run_owner = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CancelOrderFlowRun.
// This includes values selected through modifiers, order, etc.
func (_m *CancelOrderFlowRun) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the CancelOrderFlowRun entity.
func (_m *CancelOrderFlowRun) QueryOwner() *OrderQuery {
	return NewCancelOrderFlowRunClient(_m.config).QueryOwner(_m)
}

// Update returns a builder for updating this CancelOrderFlowRun.
// Note that you need to call CancelOrderFlowRun.Unwrap() before calling this method if this CancelOrderFlowRun
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CancelOrderFlowRun) Update() *CancelOrderFlowRunUpdateOne {
	return NewCancelOrderFlowRunClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CancelOrderFlowRun entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CancelOrderFlowRun) Unwrap() *CancelOrderFlowRun {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CancelOrderFlowRun is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CancelOrderFlowRun) String() string {
	var builder strings.Builder
	builder.WriteString("CancelOrderFlowRun(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteString(", ")
	builder.WriteString("input=")
	builder.WriteString(fmt.Sprintf("%v", _m.Input))
	builder.WriteString(", ")
	builder.WriteString("current_step=")
	builder.WriteString(_m.CurrentStep)
	builder.WriteString(", ")
	builder.WriteString("attempt=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attempt))
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteString(", ")
	builder.WriteString("results=")
	builder.WriteString(fmt.Sprintf("%v", _m.Results))
	builder.WriteString(", ")
	if v := _m.RetryAfter; v != nil {
		builder.WriteString("retry_after=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("trace_context=")
	builder.WriteString(_m.TraceContext)
	builder.WriteString(", ")
	builder.WriteString("self_was=")
	builder.WriteString(_m.SelfWas)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// CancelOrderFlowRuns is a parsable slice of CancelOrderFlowRun.
type CancelOrderFlowRuns []*CancelOrderFlowRun
