// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entflow/internal/testdata/ent/cancelorderflowrun"
	"github.com/smintz/entflow/internal/testdata/ent/predicate"
)

// CancelOrderFlowRunDelete is the builder for deleting a CancelOrderFlowRun entity.
type CancelOrderFlowRunDelete struct {
	config
	hooks    []Hook
	mutation *CancelOrderFlowRunMutation
}

// Where appends a list predicates to the CancelOrderFlowRunDelete builder.
func (_d *CancelOrderFlowRunDelete) Where(ps ...predicate.CancelOrderFlowRun) *CancelOrderFlowRunDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CancelOrderFlowRunDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CancelOrderFlowRunDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CancelOrderFlowRunDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(cancelorderflowrun.Table, sqlgraph.NewFieldSpec(cancelorderflowrun.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CancelOrderFlowRunDeleteOne is the builder for deleting a single CancelOrderFlowRun entity.
type CancelOrderFlowRunDeleteOne struct {
	_d *CancelOrderFlowRunDelete
}

// Where appends a list predicates to the CancelOrderFlowRunDelete builder.
func (_d *CancelOrderFlowRunDeleteOne) Where(ps ...predicate.CancelOrderFlowRun) *CancelOrderFlowRunDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CancelOrderFlowRunDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{cancelorderflowrun.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CancelOrderFlowRunDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
