// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smintz/entflow/internal/testdata/ent/cancelorderflowrun"
	"github.com/smintz/entflow/internal/testdata/ent/order"
	"github.com/smintz/entflow/internal/testdata/ent/predicate"
)

// CancelOrderFlowRunUpdate is the builder for updating CancelOrderFlowRun entities.
type CancelOrderFlowRunUpdate struct {
	config
	hooks    []Hook
	mutation *CancelOrderFlowRunMutation
}

// Where appends a list predicates to the CancelOrderFlowRunUpdate builder.
func (_u *CancelOrderFlowRunUpdate) Where(ps ...predicate.CancelOrderFlowRun) *CancelOrderFlowRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetState sets the "state" field.
func (_u *CancelOrderFlowRunUpdate) SetState(v cancelorderflowrun.State) *CancelOrderFlowRunUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *CancelOrderFlowRunUpdate) SetNillableState(v *cancelorderflowrun.State) *CancelOrderFlowRunUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetInput sets the "input" field.
func (_u *CancelOrderFlowRunUpdate) SetInput(v []byte) *CancelOrderFlowRunUpdate {
	_u.mutation.SetInput(v)
	return _u
}

// SetCurrentStep sets the "current_step" field.
func (_u *CancelOrderFlowRunUpdate) SetCurrentStep(v string) *CancelOrderFlowRunUpdate {
	_u.mutation.SetCurrentStep(v)
	return _u
}

// SetNillableCurrentStep sets the "current_step" field if the given value is not nil.
func (_u *CancelOrderFlowRunUpdate) SetNillableCurrentStep(v *string) *CancelOrderFlowRunUpdate {
	if v != nil {
		_u.SetCurrentStep(*v)
	}
	return _u
}

// ClearCurrentStep clears the value of the "current_step" field.
func (_u *CancelOrderFlowRunUpdate) ClearCurrentStep() *CancelOrderFlowRunUpdate {
	_u.mutation.ClearCurrentStep()
	return _u
}

// SetAttempt sets the "attempt" field.
func (_u *CancelOrderFlowRunUpdate) SetAttempt(v int) *CancelOrderFlowRunUpdate {
	_u.mutation.ResetAttempt()
	_u.mutation.SetAttempt(v)
	return _u
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (_u *CancelOrderFlowRunUpdate) SetNillableAttempt(v *int) *CancelOrderFlowRunUpdate {
	if v != nil {
		_u.SetAttempt(*v)
	}
	return _u
}

// AddAttempt adds value to the "attempt" field.
func (_u *CancelOrderFlowRunUpdate) AddAttempt(v int) *CancelOrderFlowRunUpdate {
	_u.mutation.AddAttempt(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *CancelOrderFlowRunUpdate) SetLastError(v string) *CancelOrderFlowRunUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *CancelOrderFlowRunUpdate) SetNillableLastError(v *string) *CancelOrderFlowRunUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *CancelOrderFlowRunUpdate) ClearLastError() *CancelOrderFlowRunUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetResults sets the "results" field.
func (_u *CancelOrderFlowRunUpdate) SetResults(v map[string]json.RawMessage) *CancelOrderFlowRunUpdate {
	_u.mutation.SetResults(v)
	return _u
}

// ClearResults clears the value of the "results" field.
func (_u *CancelOrderFlowRunUpdate) ClearResults() *CancelOrderFlowRunUpdate {
	_u.mutation.ClearResults()
	return _u
}

// SetRetryAfter sets the "retry_after" field.
func (_u *CancelOrderFlowRunUpdate) SetRetryAfter(v time.Time) *CancelOrderFlowRunUpdate {
	_u.mutation.SetRetryAfter(v)
	return _u
}

// SetNillableRetryAfter sets the "retry_after" field if the given value is not nil.
func (_u *CancelOrderFlowRunUpdate) SetNillableRetryAfter(v *time.Time) *CancelOrderFlowRunUpdate {
	if v != nil {
		_u.SetRetryAfter(*v)
	}
	return _u
}

// ClearRetryAfter clears the value of the "retry_after" field.
func (_u *CancelOrderFlowRunUpdate) ClearRetryAfter() *CancelOrderFlowRunUpdate {
	_u.mutation.ClearRetryAfter()
	return _u
}

// SetTraceContext sets the "trace_context" field.
func (_u *CancelOrderFlowRunUpdate) SetTraceContext(v string) *CancelOrderFlowRunUpdate {
	_u.mutation.SetTraceContext(v)
	return _u
}

// SetNillableTraceContext sets the "trace_context" field if the given value is not nil.
func (_u *CancelOrderFlowRunUpdate) SetNillableTraceContext(v *string) *CancelOrderFlowRunUpdate {
	if v != nil {
		_u.SetTraceContext(*v)
	}
	return _u
}

// ClearTraceContext clears the value of the "trace_context" field.
func (_u *CancelOrderFlowRunUpdate) ClearTraceContext() *CancelOrderFlowRunUpdate {
	_u.mutation.ClearTraceContext()
	return _u
}

// SetSelfWas sets the "self_was" field.
func (_u *CancelOrderFlowRunUpdate) SetSelfWas(v string) *CancelOrderFlowRunUpdate {
	_u.mutation.SetSelfWas(v)
	return _u
}

// SetNillableSelfWas sets the "self_was" field if the given value is not nil.
func (_u *CancelOrderFlowRunUpdate) SetNillableSelfWas(v *string) *CancelOrderFlowRunUpdate {
	if v != nil {
		_u.SetSelfWas(*v)
	}
	return _u
}

// ClearSelfWas clears the value of the "self_was" field.
func (_u *CancelOrderFlowRunUpdate) ClearSelfWas() *CancelOrderFlowRunUpdate {
	_u.mutation.ClearSelfWas()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CancelOrderFlowRunUpdate) SetUpdatedAt(v time.Time) *CancelOrderFlowRunUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *CancelOrderFlowRunUpdate) SetStartedAt(v time.Time) *CancelOrderFlowRunUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *CancelOrderFlowRunUpdate) SetNillableStartedAt(v *time.Time) *CancelOrderFlowRunUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *CancelOrderFlowRunUpdate) ClearStartedAt() *CancelOrderFlowRunUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *CancelOrderFlowRunUpdate) SetFinishedAt(v time.Time) *CancelOrderFlowRunUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *CancelOrderFlowRunUpdate) SetNillableFinishedAt(v *time.Time) *CancelOrderFlowRunUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *CancelOrderFlowRunUpdate) ClearFinishedAt() *CancelOrderFlowRunUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetOwnerID sets the "owner" edge to the Order entity by ID.
func (_u *CancelOrderFlowRunUpdate) SetOwnerID(id int) *CancelOrderFlowRunUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the Order entity.
func (_u *CancelOrderFlowRunUpdate) SetOwner(v *Order) *CancelOrderFlowRunUpdate {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the CancelOrderFlowRunMutation object of the builder.
func (_u *CancelOrderFlowRunUpdate) Mutation() *CancelOrderFlowRunMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the Order entity.
func (_u *CancelOrderFlowRunUpdate) ClearOwner() *CancelOrderFlowRunUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CancelOrderFlowRunUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CancelOrderFlowRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CancelOrderFlowRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CancelOrderFlowRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CancelOrderFlowRunUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cancelorderflowrun.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CancelOrderFlowRunUpdate) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := cancelorderflowrun.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "CancelOrderFlowRun.state": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CancelOrderFlowRun.owner"`)
	}
	return nil
}

func (_u *CancelOrderFlowRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cancelorderflowrun.Table, cancelorderflowrun.Columns, sqlgraph.NewFieldSpec(cancelorderflowrun.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(cancelorderflowrun.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Input(); ok {
		_spec.SetField(cancelorderflowrun.FieldInput, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.CurrentStep(); ok {
		_spec.SetField(cancelorderflowrun.FieldCurrentStep, field.TypeString, value)
	}
	if _u.mutation.CurrentStepCleared() {
		_spec.ClearField(cancelorderflowrun.FieldCurrentStep, field.TypeString)
	}
	if value, ok := _u.mutation.Attempt(); ok {
		_spec.SetField(cancelorderflowrun.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempt(); ok {
		_spec.AddField(cancelorderflowrun.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(cancelorderflowrun.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(cancelorderflowrun.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.Results(); ok {
		_spec.SetField(cancelorderflowrun.FieldResults, field.TypeJSON, value)
	}
	if _u.mutation.ResultsCleared() {
		_spec.ClearField(cancelorderflowrun.FieldResults, field.TypeJSON)
	}
	if value, ok := _u.mutation.RetryAfter(); ok {
		_spec.SetField(cancelorderflowrun.FieldRetryAfter, field.TypeTime, value)
	}
	if _u.mutation.RetryAfterCleared() {
		_spec.ClearField(cancelorderflowrun.FieldRetryAfter, field.TypeTime)
	}
	if value, ok := _u.mutation.TraceContext(); ok {
		_spec.SetField(cancelorderflowrun.FieldTraceContext, field.TypeString, value)
	}
	if _u.mutation.TraceContextCleared() {
		_spec.ClearField(cancelorderflowrun.FieldTraceContext, field.TypeString)
	}
	if value, ok := _u.mutation.SelfWas(); ok {
		_spec.SetField(cancelorderflowrun.FieldSelfWas, field.TypeString, value)
	}
	if _u.mutation.SelfWasCleared() {
		_spec.ClearField(cancelorderflowrun.FieldSelfWas, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cancelorderflowrun.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(cancelorderflowrun.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(cancelorderflowrun.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(cancelorderflowrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(cancelorderflowrun.FieldFinishedAt, field.TypeTime)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   cancelorderflowrun.OwnerTable,
			Columns: []string{cancelorderflowrun.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   cancelorderflowrun.OwnerTable,
			Columns: []string{cancelorderflowrun.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cancelorderflowrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CancelOrderFlowRunUpdateOne is the builder for updating a single CancelOrderFlowRun entity.
type CancelOrderFlowRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CancelOrderFlowRunMutation
}

// SetState sets the "state" field.
func (_u *CancelOrderFlowRunUpdateOne) SetState(v cancelorderflowrun.State) *CancelOrderFlowRunUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *CancelOrderFlowRunUpdateOne) SetNillableState(v *cancelorderflowrun.State) *CancelOrderFlowRunUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetInput sets the "input" field.
func (_u *CancelOrderFlowRunUpdateOne) SetInput(v []byte) *CancelOrderFlowRunUpdateOne {
	_u.mutation.SetInput(v)
	return _u
}

// SetCurrentStep sets the "current_step" field.
func (_u *CancelOrderFlowRunUpdateOne) SetCurrentStep(v string) *CancelOrderFlowRunUpdateOne {
	_u.mutation.SetCurrentStep(v)
	return _u
}

// SetNillableCurrentStep sets the "current_step" field if the given value is not nil.
func (_u *CancelOrderFlowRunUpdateOne) SetNillableCurrentStep(v *string) *CancelOrderFlowRunUpdateOne {
	if v != nil {
		_u.SetCurrentStep(*v)
	}
	return _u
}

// ClearCurrentStep clears the value of the "current_step" field.
func (_u *CancelOrderFlowRunUpdateOne) ClearCurrentStep() *CancelOrderFlowRunUpdateOne {
	_u.mutation.ClearCurrentStep()
	return _u
}

// SetAttempt sets the "attempt" field.
func (_u *CancelOrderFlowRunUpdateOne) SetAttempt(v int) *CancelOrderFlowRunUpdateOne {
	_u.mutation.ResetAttempt()
	_u.mutation.SetAttempt(v)
	return _u
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (_u *CancelOrderFlowRunUpdateOne) SetNillableAttempt(v *int) *CancelOrderFlowRunUpdateOne {
	if v != nil {
		_u.SetAttempt(*v)
	}
	return _u
}

// AddAttempt adds value to the "attempt" field.
func (_u *CancelOrderFlowRunUpdateOne) AddAttempt(v int) *CancelOrderFlowRunUpdateOne {
	_u.mutation.AddAttempt(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *CancelOrderFlowRunUpdateOne) SetLastError(v string) *CancelOrderFlowRunUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *CancelOrderFlowRunUpdateOne) SetNillableLastError(v *string) *CancelOrderFlowRunUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *CancelOrderFlowRunUpdateOne) ClearLastError() *CancelOrderFlowRunUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetResults sets the "results" field.
func (_u *CancelOrderFlowRunUpdateOne) SetResults(v map[string]json.RawMessage) *CancelOrderFlowRunUpdateOne {
	_u.mutation.SetResults(v)
	return _u
}

// ClearResults clears the value of the "results" field.
func (_u *CancelOrderFlowRunUpdateOne) ClearResults() *CancelOrderFlowRunUpdateOne {
	_u.mutation.ClearResults()
	return _u
}

// SetRetryAfter sets the "retry_after" field.
func (_u *CancelOrderFlowRunUpdateOne) SetRetryAfter(v time.Time) *CancelOrderFlowRunUpdateOne {
	_u.mutation.SetRetryAfter(v)
	return _u
}

// SetNillableRetryAfter sets the "retry_after" field if the given value is not nil.
func (_u *CancelOrderFlowRunUpdateOne) SetNillableRetryAfter(v *time.Time) *CancelOrderFlowRunUpdateOne {
	if v != nil {
		_u.SetRetryAfter(*v)
	}
	return _u
}

// ClearRetryAfter clears the value of the "retry_after" field.
func (_u *CancelOrderFlowRunUpdateOne) ClearRetryAfter() *CancelOrderFlowRunUpdateOne {
	_u.mutation.ClearRetryAfter()
	return _u
}

// SetTraceContext sets the "trace_context" field.
func (_u *CancelOrderFlowRunUpdateOne) SetTraceContext(v string) *CancelOrderFlowRunUpdateOne {
	_u.mutation.SetTraceContext(v)
	return _u
}

// SetNillableTraceContext sets the "trace_context" field if the given value is not nil.
func (_u *CancelOrderFlowRunUpdateOne) SetNillableTraceContext(v *string) *CancelOrderFlowRunUpdateOne {
	if v != nil {
		_u.SetTraceContext(*v)
	}
	return _u
}

// ClearTraceContext clears the value of the "trace_context" field.
func (_u *CancelOrderFlowRunUpdateOne) ClearTraceContext() *CancelOrderFlowRunUpdateOne {
	_u.mutation.ClearTraceContext()
	return _u
}

// SetSelfWas sets the "self_was" field.
func (_u *CancelOrderFlowRunUpdateOne) SetSelfWas(v string) *CancelOrderFlowRunUpdateOne {
	_u.mutation.SetSelfWas(v)
	return _u
}

// SetNillableSelfWas sets the "self_was" field if the given value is not nil.
func (_u *CancelOrderFlowRunUpdateOne) SetNillableSelfWas(v *string) *CancelOrderFlowRunUpdateOne {
	if v != nil {
		_u.SetSelfWas(*v)
	}
	return _u
}

// ClearSelfWas clears the value of the "self_was" field.
func (_u *CancelOrderFlowRunUpdateOne) ClearSelfWas() *CancelOrderFlowRunUpdateOne {
	_u.mutation.ClearSelfWas()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CancelOrderFlowRunUpdateOne) SetUpdatedAt(v time.Time) *CancelOrderFlowRunUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *CancelOrderFlowRunUpdateOne) SetStartedAt(v time.Time) *CancelOrderFlowRunUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *CancelOrderFlowRunUpdateOne) SetNillableStartedAt(v *time.Time) *CancelOrderFlowRunUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *CancelOrderFlowRunUpdateOne) ClearStartedAt() *CancelOrderFlowRunUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *CancelOrderFlowRunUpdateOne) SetFinishedAt(v time.Time) *CancelOrderFlowRunUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *CancelOrderFlowRunUpdateOne) SetNillableFinishedAt(v *time.Time) *CancelOrderFlowRunUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *CancelOrderFlowRunUpdateOne) ClearFinishedAt() *CancelOrderFlowRunUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetOwnerID sets the "owner" edge to the Order entity by ID.
func (_u *CancelOrderFlowRunUpdateOne) SetOwnerID(id int) *CancelOrderFlowRunUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the Order entity.
func (_u *CancelOrderFlowRunUpdateOne) SetOwner(v *Order) *CancelOrderFlowRunUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the CancelOrderFlowRunMutation object of the builder.
func (_u *CancelOrderFlowRunUpdateOne) Mutation() *CancelOrderFlowRunMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the Order entity.
func (_u *CancelOrderFlowRunUpdateOne) ClearOwner() *CancelOrderFlowRunUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// Where appends a list predicates to the CancelOrderFlowRunUpdate builder.
func (_u *CancelOrderFlowRunUpdateOne) Where(ps ...predicate.CancelOrderFlowRun) *CancelOrderFlowRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CancelOrderFlowRunUpdateOne) Select(field string, fields ...string) *CancelOrderFlowRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CancelOrderFlowRun entity.
func (_u *CancelOrderFlowRunUpdateOne) Save(ctx context.Context) (*CancelOrderFlowRun, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CancelOrderFlowRunUpdateOne) SaveX(ctx context.Context) *CancelOrderFlowRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CancelOrderFlowRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CancelOrderFlowRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CancelOrderFlowRunUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cancelorderflowrun.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CancelOrderFlowRunUpdateOne) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := cancelorderflowrun.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "CancelOrderFlowRun.state": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CancelOrderFlowRun.owner"`)
	}
	return nil
}

func (_u *CancelOrderFlowRunUpdateOne) sqlSave(ctx context.Context) (_node *CancelOrderFlowRun, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cancelorderflowrun.Table, cancelorderflowrun.Columns, sqlgraph.NewFieldSpec(cancelorderflowrun.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CancelOrderFlowRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cancelorderflowrun.FieldID)
		for _, f := range fields {
			if !cancelorderflowrun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cancelorderflowrun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(cancelorderflowrun.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Input(); ok {
		_spec.SetField(cancelorderflowrun.FieldInput, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.CurrentStep(); ok {
		_spec.SetField(cancelorderflowrun.FieldCurrentStep, field.TypeString, value)
	}
	if _u.mutation.CurrentStepCleared() {
		_spec.ClearField(cancelorderflowrun.FieldCurrentStep, field.TypeString)
	}
	if value, ok := _u.mutation.Attempt(); ok {
		_spec.SetField(cancelorderflowrun.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempt(); ok {
		_spec.AddField(cancelorderflowrun.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(cancelorderflowrun.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(cancelorderflowrun.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.Results(); ok {
		_spec.SetField(cancelorderflowrun.FieldResults, field.TypeJSON, value)
	}
	if _u.mutation.ResultsCleared() {
		_spec.ClearField(cancelorderflowrun.FieldResults, field.TypeJSON)
	}
	if value, ok := _u.mutation.RetryAfter(); ok {
		_spec.SetField(cancelorderflowrun.FieldRetryAfter, field.TypeTime, value)
	}
	if _u.mutation.RetryAfterCleared() {
		_spec.ClearField(cancelorderflowrun.FieldRetryAfter, field.TypeTime)
	}
	if value, ok := _u.mutation.TraceContext(); ok {
		_spec.SetField(cancelorderflowrun.FieldTraceContext, field.TypeString, value)
	}
	if _u.mutation.TraceContextCleared() {
		_spec.ClearField(cancelorderflowrun.FieldTraceContext, field.TypeString)
	}
	if value, ok := _u.mutation.SelfWas(); ok {
		_spec.SetField(cancelorderflowrun.FieldSelfWas, field.TypeString, value)
	}
	if _u.mutation.SelfWasCleared() {
		_spec.ClearField(cancelorderflowrun.FieldSelfWas, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cancelorderflowrun.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(cancelorderflowrun.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(cancelorderflowrun.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(cancelorderflowrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(cancelorderflowrun.FieldFinishedAt, field.TypeTime)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   cancelorderflowrun.OwnerTable,
			Columns: []string{cancelorderflowrun.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   cancelorderflowrun.OwnerTable,
			Columns: []string{cancelorderflowrun.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CancelOrderFlowRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cancelorderflowrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
