// Code generated by ent, DO NOT EDIT.

package order

import (
	"entgo.io/ent/dialect/sql"
	"github.com/smintz/entflow/internal/testdata/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldID, id))
}

// PaymentIntentID applies equality check predicate on the "payment_intent_id" field. It's identical to PaymentIntentIDEQ.
func PaymentIntentID(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldPaymentIntentID, v))
}

// PaymentIntentIDEQ applies the EQ predicate on the "payment_intent_id" field.
func PaymentIntentIDEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldPaymentIntentID, v))
}

// PaymentIntentIDNEQ applies the NEQ predicate on the "payment_intent_id" field.
func PaymentIntentIDNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldPaymentIntentID, v))
}

// PaymentIntentIDIn applies the In predicate on the "payment_intent_id" field.
func PaymentIntentIDIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldPaymentIntentID, vs...))
}

// PaymentIntentIDNotIn applies the NotIn predicate on the "payment_intent_id" field.
func PaymentIntentIDNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldPaymentIntentID, vs...))
}

// PaymentIntentIDGT applies the GT predicate on the "payment_intent_id" field.
func PaymentIntentIDGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldPaymentIntentID, v))
}

// PaymentIntentIDGTE applies the GTE predicate on the "payment_intent_id" field.
func PaymentIntentIDGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldPaymentIntentID, v))
}

// PaymentIntentIDLT applies the LT predicate on the "payment_intent_id" field.
func PaymentIntentIDLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldPaymentIntentID, v))
}

// PaymentIntentIDLTE applies the LTE predicate on the "payment_intent_id" field.
func PaymentIntentIDLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldPaymentIntentID, v))
}

// PaymentIntentIDContains applies the Contains predicate on the "payment_intent_id" field.
func PaymentIntentIDContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldPaymentIntentID, v))
}

// PaymentIntentIDHasPrefix applies the HasPrefix predicate on the "payment_intent_id" field.
func PaymentIntentIDHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldPaymentIntentID, v))
}

// PaymentIntentIDHasSuffix applies the HasSuffix predicate on the "payment_intent_id" field.
func PaymentIntentIDHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldPaymentIntentID, v))
}

// PaymentIntentIDIsNil applies the IsNil predicate on the "payment_intent_id" field.
func PaymentIntentIDIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldPaymentIntentID))
}

// PaymentIntentIDNotNil applies the NotNil predicate on the "payment_intent_id" field.
func PaymentIntentIDNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldPaymentIntentID))
}

// PaymentIntentIDEqualFold applies the EqualFold predicate on the "payment_intent_id" field.
func PaymentIntentIDEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldPaymentIntentID, v))
}

// PaymentIntentIDContainsFold applies the ContainsFold predicate on the "payment_intent_id" field.
func PaymentIntentIDContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldPaymentIntentID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldStatus, vs...))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Order) predicate.Order {
	return predicate.Order(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Order) predicate.Order {
	return predicate.Order(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Order) predicate.Order {
	return predicate.Order(sql.NotPredicates(p))
}
