// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"github.com/smintz/entflow/internal/testdata/ent/order"
	"github.com/smintz/entflow/internal/testdata/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	orderHooks := schema.Order{}.Hooks()
	order.Hooks[0] = orderHooks[0]
	orderFields := schema.Order{}.Fields()
	_ = orderFields
}

const (
	Version = "v0.14.6"                                         // Version of ent codegen.
	Sum     = "h1:/f2696BpwuWAEEG6PVGWflg6+Inrpq4pRWuNlWz/Skk=" // Sum of ent codegen.
)
