// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CancelOrderFlowRun is the predicate function for cancelorderflowrun builders.
type CancelOrderFlowRun func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)
